name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install
        run: npm ci || npm install
      - name: Lint
        run: npm run -s lint
      - name: Test
        run: npm test --silent
      - name: Build
        run: npm run build
        env:
          VITE_COPILOT_BOT_ID: ${{ vars.VITE_COPILOT_BOT_ID || secrets.VITE_COPILOT_BOT_ID }}
          VITE_COPILOT_TENANT_ID: ${{ vars.VITE_COPILOT_TENANT_ID || secrets.VITE_COPILOT_TENANT_ID }}
          VITE_COPILOT_DIRECT_URL: ${{ vars.VITE_COPILOT_DIRECT_URL || secrets.VITE_COPILOT_DIRECT_URL }}
          VITE_COPILOT_ENV_ID: ${{ vars.VITE_COPILOT_ENV_ID || secrets.VITE_COPILOT_ENV_ID }}
          VITE_COPILOT_SCHEMA: ${{ vars.VITE_COPILOT_SCHEMA || secrets.VITE_COPILOT_SCHEMA }}
          VITE_ENTRA_CLIENT_ID: ${{ vars.VITE_ENTRA_CLIENT_ID || secrets.VITE_ENTRA_CLIENT_ID }}
          VITE_ENTRA_AUTHORITY: ${{ vars.VITE_ENTRA_AUTHORITY || secrets.VITE_ENTRA_AUTHORITY }}
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/' 
          output_location: 'dist'

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: 'close'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
